trigger: 
- none

pr: none

variables:
- name: devEnvironment
  value: dev

resources:
  pipelines:
  - pipeline: 'ci-pipeline'
    # TODO: Update with the name of your CI pipeline
    source: 'CI'
    trigger:
      branches:
      - workflow

stages:
- stage: DEV
  displayName: 'DEV Deployment'
  variables:
  - template: variables/pipeline-vars.yml
  jobs:
  - deployment: deploy_logicapp_resources
    displayName: Deploy Logic App
    pool:
      vmImage: ubuntu-latest
    environment: $(devEnvironment)
    variables:
      deploymentMode: 'Incremental'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureAppServiceSettings@1
            displayName: Azure App Service Settings
            inputs:
              azureSubscription: 'Az_DevOps_Pipeline'
              appName: '$(logicAppName)'
              resourceGroupName: '$(resourceGroupName)'
              
              # Add the app settings for the connections 
            
              appSettings: |
                [
                    {
                    "name": "AzureFunctionsJobHost__extensionBundle__version",
                    "value": "[1.*, 2.0.0)"
                    },
                    {
                    "name": "FUNCTIONS_EXTENSION_VERSION",
                    "value": "~3"
                    },
                    {
                    "name": "FUNCTIONS_V2_COMPATIBILITY_MODE",
                    "value": "true"
                    },
                    {
                    "name": "FUNCTIONS_WORKER_RUNTIME",
                    "value": "node"
                    },
                    {
                    "name": "WORKFLOWS_SUBSCRIPTION_ID",
                    "value": "0f3ae6f5-ea70-4968-a345-b293198b61df"
                    },
                    {
                    "name": "WORKFLOWS_RESOURCE_GROUP_NAME",
                    "value": "PnG_terraform_testing"
                    },
                    {
                    "name": "WORKFLOWS_LOCATION_NAME",
                    "value": "centralus"
                    }                    
                ]
          - task: AzureFunctionApp@1
            displayName: 'Deploy logic app workflows'
            inputs:
              # TODO: Fill in with the name of your Azure service connection
              azureSubscription: 'Az_DevOps_Pipeline'
              appType: 'functionApp'
              appName: '$(logicAppName)'
              package: '$(Pipeline.Workspace)/cipipeline/$(logicAppCIArtifactName)/$(resources.pipeline.cipipeline.runID).zip'
              deploymentMethod: 'zipDeploy'
