# IaC Logic App resources deployment template

parameters:
- name: environment
  type: string
- name: serviceConnection
  type: string

jobs:
- deployment: deploy_logicapp_connector_resources
  displayName: Deploy Logic App Connector Resources
  pool:
    vmImage: ubuntu-latest
  environment: ${{ parameters.environment }}
  variables:
    deploymentMode: 'Incremental'
  strategy:
    runOnce:
      deploy:
        steps:
        - download: current
          artifact: $(artifactName)
      # Extract files
# Extract a variety of archive and compression files such as .7z, .rar, .tar.gz, and .zip
        - task: ExtractFiles@1
          displayName: 'Extract Zip contents'
          inputs:
            archiveFilePatterns: '$(Pipeline.Workspace)/**/*.zip' 
            destinationFolder: '$(Pipeline.Workspace)/extracted'
            #cleanDestinationFolder: true 
            #overwriteExistingFiles: false
            #pathToSevenZipTool:

        - task: AzureResourceGroupDeployment@2
          displayName: 'Deploy Connectors'
          inputs:
            azureSubscription: ${{ parameters.serviceConnection }}
            resourceGroupName: $(resourceGroupName)
            location: $(resourceGroupLocation)
           #csmFile: '$(Pipeline.Workspace)/$(artifactName)/connections.json'
            csmFile: '$(Pipeline.Workspace)/extracted/connections.json'
            overrideParameters: '
              -location $(resourceGroupLocation)
              -connections_azureblob_name $(blobConnectionName)
              -logicAppSystemAssignedIdentityTenantId $(logicAppSystemAssignedIdentityTenantId)
              -logicAppSystemAssignedIdentityObjectId $(logicAppSystemAssignedIdentityObjectId)
              -storageName $(storageName)'
            deploymentMode: $(deploymentMode)

        - task: ARM Outputs@6
          displayName: 'ARM Outputs Connections'
          inputs:
            ConnectedServiceNameSelector: 'ConnectedServiceNameARM'
            ConnectedServiceNameARM: ${{ parameters.serviceConnection }}
            resourceGroupName: $(resourceGroupName)
            whenLastDeploymentIsFailed: 'fail'

        - task: AzureCLI@2
          inputs:
            azureSubscription: ${{ parameters.serviceConnection }}
            scriptType: 'bash'
            scriptLocation: 'inlineScript'
            inlineScript: |
              az functionapp config appsettings set --name $(logicAppName) --resource-group  $(resourceGroupName) --settings "BLOB_CONNECTION_RUNTIMEURL=$(blobendpointurl)"
              az functionapp config appsettings set --name $(logicAppName) --resource-group  $(resourceGroupName) --settings "WORKFLOWS_RESOURCE_GROUP_NAME=$(resourceGroupName)"
            addSpnToEnvironment: true
            useGlobalConfig: true